### ISSUE TITLE
Installation Failed on macOS Big Sur

### ISSUE THREAD

**Issue by dw61** [50Wliu/language-hclrs#3]
I am working on [this](https://www.cs.virginia.edu/~cr4bd/3330/F2021/hcl2.html) homework using hclrs. I tried to install this package in atom using graphic user interface, but installation failed. Here's the atom output

```
> tree-sitter-hclrs@0.0.2 install /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/tree-sitter-hclrs
> node-gyp rebuild

  CC(target) Release/obj.target/tree_sitter_hclrs_binding/src/parser.o
  CXX(target) Release/obj.target/tree_sitter_hclrs_binding/src/binding.o

../src/binding.cc:13:11: error: no template named 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
          ^
../src/binding.cc:13:35: error: no template named 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
                                  ^
../src/binding.cc:18:50: error: too few arguments to function call, single argument 'context' was not specified
  Local<Function> constructor = tpl->GetFunction();
                                ~~~~~~~~~~~~~~~~ ^
/Users/wlt/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:6474:46: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                             ^
../src/binding.cc:22:13: error: no matching member function for call to 'Set'
  instance->Set(Nan::New("name").ToLocalChecked(), Nan::New("hclrs").ToLocalChecked());
  ~~~~~~~~~~^~~
/Users/wlt/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/wlt/.atom/.node-gyp/Library/Caches/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/tree_sitter_hclrs_binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/tree-sitter-hclrs
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/package.json'
npm WARN apm-install-dir-2021822-30287-1xezp5m.zcuz No description
npm WARN apm-install-dir-2021822-30287-1xezp5m.zcuz No repository field.
npm WARN apm-install-dir-2021822-30287-1xezp5m.zcuz No README data
npm WARN apm-install-dir-2021822-30287-1xezp5m.zcuz No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-hclrs@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-hclrs@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wlt/.atom/.apm/_logs/2021-09-23T00_01_39_675Z-debug.log
```

and here is the log from `/Users/wlt/.atom/.apm/_logs/2021-09-23T00_01_39_675Z-debug.log`.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/wlt/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/wlt/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/language-hclrs/versions/0.0.1/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session 8b2fb5f6f22e9436
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/50Wliu/language-hclrs/legacy.tar.gz/refs/tags/v0.0.1 358ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/language-hclrs/versions/0.0.1/tarball fetched in 375ms
9 timing stage:loadCurrentTree Completed in 384ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule language-hclrs@0.0.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/tree-sitter-hclrs 614ms (from cache)
18 silly pacote range manifest for tree-sitter-hclrs@^0.0.2 fetched in 618ms
19 silly resolveWithNewModule tree-sitter-hclrs@0.0.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/nan 86ms (from cache)
21 silly pacote range manifest for nan@^2.12.1 fetched in 89ms
22 silly resolveWithNewModule nan@2.15.0 checking installable status
23 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 715ms
24 timing stage:loadIdealTree Completed in 717ms
25 silly currentTree apm-install-dir-2021822-30287-1xezp5m.zcuz
26 silly idealTree apm-install-dir-2021822-30287-1xezp5m.zcuz
26 silly idealTree `-- language-hclrs@0.0.1
26 silly idealTree   +-- nan@2.15.0
26 silly idealTree   `-- tree-sitter-hclrs@0.0.2
27 silly install generateActionsToTake
28 silly diff-trees filtering actions: includeDev false includeProd true includeOpt true
29 timing stage:generateActionsToTake Completed in 3ms
30 silly diffTrees action count 3
31 silly diffTrees add nan@2.15.0
32 silly diffTrees add tree-sitter-hclrs@0.0.2
33 silly diffTrees add language-hclrs@0.0.1
34 silly decomposeActions action count 24
35 silly decomposeActions fetch nan@2.15.0
36 silly decomposeActions extract nan@2.15.0
37 silly decomposeActions preinstall nan@2.15.0
38 silly decomposeActions build nan@2.15.0
39 silly decomposeActions install nan@2.15.0
40 silly decomposeActions postinstall nan@2.15.0
41 silly decomposeActions finalize nan@2.15.0
42 silly decomposeActions refresh-package-json nan@2.15.0
43 silly decomposeActions fetch tree-sitter-hclrs@0.0.2
44 silly decomposeActions extract tree-sitter-hclrs@0.0.2
45 silly decomposeActions preinstall tree-sitter-hclrs@0.0.2
46 silly decomposeActions build tree-sitter-hclrs@0.0.2
47 silly decomposeActions install tree-sitter-hclrs@0.0.2
48 silly decomposeActions postinstall tree-sitter-hclrs@0.0.2
49 silly decomposeActions finalize tree-sitter-hclrs@0.0.2
50 silly decomposeActions refresh-package-json tree-sitter-hclrs@0.0.2
51 silly decomposeActions fetch language-hclrs@0.0.1
52 silly decomposeActions extract language-hclrs@0.0.1
53 silly decomposeActions preinstall language-hclrs@0.0.1
54 silly decomposeActions build language-hclrs@0.0.1
55 silly decomposeActions install language-hclrs@0.0.1
56 silly decomposeActions postinstall language-hclrs@0.0.1
57 silly decomposeActions finalize language-hclrs@0.0.1
58 silly decomposeActions refresh-package-json language-hclrs@0.0.1
59 silly install executeActions
60 silly doSerial global-install 24
61 verbose correctMkdir /Users/wlt/.atom/.apm/_locks correctMkdir not in flight; initializing
62 verbose lock using /Users/wlt/.atom/.apm/_locks/staging-170781f8a5bba11e.lock for /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/.staging
63 silly doParallel extract 3
64 silly extract nan@2.15.0
65 silly extract tree-sitter-hclrs@0.0.2
66 silly extract language-hclrs@0.0.1
67 silly tarball trying nan@^2.12.1 by hash: sha512-8ZtvEnA2c5aYCZYd1cvgdnU6cqwixRoYg70xPLWUws5ORTa/lnw+u4amixRS/Ac5U5mQVgp9pnlSUnbNWFaWZQ==
68 silly tarball trying tree-sitter-hclrs@^0.0.2 by hash: sha512-kfi36hu3xJR/Tz+TzEAz9uCWEOnny1csrw6PmVCxdaW/J8DOfdpPo3ai9zVdXk91rn9LrMOglfVLomSIYvAf4w==
69 silly tarball trying https://www.atom.io/api/packages/language-hclrs/versions/0.0.1/tarball by hash: sha512-NE9YJZY26ZIg9EXURLvGMM+HuHOyGsNNGa3lF6h0iN81ULbT6nViw/bocI8ClncQX6dw9BE4F2/KuUDT7h4HqA==
70 silly extract https://www.atom.io/api/packages/language-hclrs/versions/0.0.1/tarball extracted to /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/.staging/language-hclrs-8eb7d0cb (27ms)
71 silly extract tree-sitter-hclrs@^0.0.2 extracted to /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/.staging/tree-sitter-hclrs-023d4e4d (30ms)
72 silly extract nan@^2.12.1 extracted to /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/.staging/nan-40d683d0 (36ms)
73 timing action:extract Completed in 38ms
74 silly doReverseSerial unbuild 24
75 silly doSerial remove 24
76 silly doSerial move 24
77 silly doSerial finalize 24
78 silly finalize /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/nan
79 silly finalize /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/tree-sitter-hclrs
80 silly finalize /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs
81 timing action:finalize Completed in 7ms
82 silly doParallel refresh-package-json 3
83 silly refresh-package-json /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/nan
84 silly refresh-package-json /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/tree-sitter-hclrs
85 silly refresh-package-json /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs
86 timing action:refresh-package-json Completed in 12ms
87 silly doParallel preinstall 3
88 silly preinstall nan@2.15.0
89 info lifecycle nan@2.15.0~preinstall: nan@2.15.0
90 silly preinstall tree-sitter-hclrs@0.0.2
91 info lifecycle tree-sitter-hclrs@0.0.2~preinstall: tree-sitter-hclrs@0.0.2
92 silly preinstall language-hclrs@0.0.1
93 info lifecycle language-hclrs@0.0.1~preinstall: language-hclrs@0.0.1
94 timing action:preinstall Completed in 1ms
95 silly doSerial build 24
96 silly build nan@2.15.0
97 info linkStuff nan@2.15.0
98 silly linkStuff nan@2.15.0 has /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules as its parent node_modules
99 silly build tree-sitter-hclrs@0.0.2
100 info linkStuff tree-sitter-hclrs@0.0.2
101 silly linkStuff tree-sitter-hclrs@0.0.2 has /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules as its parent node_modules
102 silly build language-hclrs@0.0.1
103 info linkStuff language-hclrs@0.0.1
104 silly linkStuff language-hclrs@0.0.1 has /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules as its parent node_modules
105 timing action:build Completed in 1ms
106 silly doSerial global-link 24
107 silly doParallel update-linked 0
108 silly doSerial install 24
109 silly install nan@2.15.0
110 info lifecycle nan@2.15.0~install: nan@2.15.0
111 silly install tree-sitter-hclrs@0.0.2
112 info lifecycle tree-sitter-hclrs@0.0.2~install: tree-sitter-hclrs@0.0.2
113 verbose lifecycle tree-sitter-hclrs@0.0.2~install: unsafe-perm in lifecycle true
114 verbose lifecycle tree-sitter-hclrs@0.0.2~install: PATH: /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/tree-sitter-hclrs/node_modules/.bin:/private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/.bin:/private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/.bin:/Applications/Atom.app/Contents/Resources/app/apm/bin:/Users/wlt/.cargo/bin:/usr/local/opt/ruby/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/llvm/bin:/Users/wlt/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin
115 verbose lifecycle tree-sitter-hclrs@0.0.2~install: CWD: /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/language-hclrs/node_modules/tree-sitter-hclrs
116 silly lifecycle tree-sitter-hclrs@0.0.2~install: Args: [ '-c', 'node-gyp rebuild' ]
117 timing audit submit Completed in 148ms
118 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 148ms
119 timing audit body Completed in 0ms
120 silly lifecycle tree-sitter-hclrs@0.0.2~install: Returned: code: 1  signal: null
121 info lifecycle tree-sitter-hclrs@0.0.2~install: Failed to exec install script
122 timing action:install Completed in 5500ms
123 verbose unlock done using /Users/wlt/.atom/.apm/_locks/staging-170781f8a5bba11e.lock for /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/node_modules/.staging
124 timing stage:rollbackFailedOptional Completed in 17ms
125 timing stage:runTopLevelLifecycles Completed in 6691ms
126 silly saveTree apm-install-dir-2021822-30287-1xezp5m.zcuz
126 silly saveTree `-- language-hclrs@0.0.1
126 silly saveTree   `-- tree-sitter-hclrs@0.0.2
126 silly saveTree     `-- nan@2.15.0
127 warn enoent ENOENT: no such file or directory, open '/private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz/package.json'
128 verbose enoent This is related to npm not being able to find a file.
129 warn apm-install-dir-2021822-30287-1xezp5m.zcuz No description
130 warn apm-install-dir-2021822-30287-1xezp5m.zcuz No repository field.
131 warn apm-install-dir-2021822-30287-1xezp5m.zcuz No README data
132 warn apm-install-dir-2021822-30287-1xezp5m.zcuz No license field.
133 verbose stack Error: tree-sitter-hclrs@0.0.2 install: `node-gyp rebuild`
133 verbose stack Exit status 1
133 verbose stack     at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
133 verbose stack     at EventEmitter.emit (events.js:223:5)
133 verbose stack     at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
133 verbose stack     at ChildProcess.emit (events.js:223:5)
133 verbose stack     at maybeClose (internal/child_process.js:1021:16)
133 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
134 verbose pkgid tree-sitter-hclrs@0.0.2
135 verbose cwd /private/var/folders/8h/6s_k0gw516x_vhfgp65791w00000gn/T/apm-install-dir-2021822-30287-1xezp5m.zcuz
136 verbose Darwin 20.6.0
137 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/wlt/.atom/.apm/.apmrc" "--userconfig" "/Users/wlt/.atom/.apmrc" "install" "https://www.atom.io/api/packages/language-hclrs/versions/0.0.1/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
138 verbose node v12.14.1
139 verbose npm  v6.14.13
140 error code ELIFECYCLE
141 error errno 1
142 error tree-sitter-hclrs@0.0.2 install: `node-gyp rebuild`
142 error Exit status 1
143 error Failed at the tree-sitter-hclrs@0.0.2 install script.
143 error This is probably not a problem with npm. There is likely additional logging output above.
144 verbose exit [ 1, true ]
```

I tried re-install xcode-select as per [this](https://stackoverflow.com/questions/60573595/npm-install-fails-on-node-gyp-rebuild-with-gyp-no-xcode-or-clt-version-detec) link, but can't solve the package installation error. Any hints?

Thanks!

**Comment by winstliu** [comment]
Oof, it's been a while since I've seen these errors...but it looks like a Node incompatibility. Perhaps I need to update some dependencies? Will look into it and see how successful I am...

**Comment by dw61** [comment]
Great! Thanks for the continued support!

**Comment by winstliu** [comment]
Just released language-hclrs@0.0.2, could you try updating/re-installing and seeing if that fixes the error?

**Comment by dw61** [comment]
Hmmm. I successfully installed the package, and at the bottom right of my atom editor, it says file uses HCLRS grammar. However, I don't see any syntax highlighting or autocomplete. Is that something this package is supposed to do?

<img width="1440" alt="Screen Shot 2021-09-27 at 08 13 44" src="https://user-images.githubusercontent.com/27620726/134905822-8c744183-eb18-49c6-8b1e-fd5d7989a520.png">

**Comment by winstliu** [comment]
Well, boo :(. Syntax highlighting is _exactly_ what this package is supposed to do :). Not sure what might be causing the issue...I will try to take a look later.

In the meantime, can you please:
1. Open a new issue for this?
2. Position your cursor over a comment and let me know what scopes are being used? (I forget the exact command, but you should be able to search the Command Palette for "Scope" and hopefully the right one will pop up.)

(Also, seeing that `pc = P_pc` line brings back memories of late-night debugging that I'd rather not remember 😆)

**Comment by dw61** [comment]
Of course! This package will definitely make my 3330 life better lol
